[[main]]
  name = "GitHub"
  url = "https://github.com/consulkvcommander/consulkvcommander"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/yashvardhan-kukreja/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/yashkukreja98"
  weight = 30
